name: CI tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify docker
        run: docker ps -a

      - name: Run tests
        run: ./in-docker.sh 'yarn install && yarn test'
