name: CI tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker run --rm -it -v $PWD:/app suchipi/node-nw-env:0.5.2 bash -c 'Xvfb -screen 0 1024x768x16 -ac & source /usr/local/nvm/nvm.sh && cd /app && nvm use && yarn install && yarn test'
